version: '3'

services:
  caldera-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: caldera-backend:latest
    ports:
      - "8888:8888"
    environment:
      - CALDERA_RED_ADMIN_PASSWORD=admin
      - CALDERA_BLUE_ADMIN_PASSWORD=admin
    command: python server.py --insecure
